"""table

Revision ID: 0bc3f2cc3a80
Revises: 
Create Date: 2020-05-16 17:00:32.918608

"""
from alembic import op
import sqlalchemy as sa
import werewolf

# revision identifiers, used by Alembic.
revision = '0bc3f2cc3a80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('gid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_uid', sa.Integer(), nullable=False),
    sa.Column('status', werewolf.models.base.EnumType(), nullable=False),
    sa.Column('victory_mode', werewolf.models.base.EnumType(), nullable=False),
    sa.Column('captain_mode', werewolf.models.base.EnumType(), nullable=False),
    sa.Column('witch_mode', werewolf.models.base.EnumType(), nullable=False),
    sa.Column('wolf_mode', werewolf.models.base.EnumType(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('players', werewolf.models.base.JSONEncodedType(length=225), nullable=False),
    sa.Column('cards', werewolf.models.base.JSONEncodedType(length=1023), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('now_index', sa.Integer(), nullable=False),
    sa.Column('step_cnt', sa.Integer(), nullable=False),
    sa.Column('steps', werewolf.models.base.JSONEncodedType(length=1023), nullable=False),
    sa.Column('history', werewolf.models.base.JSONEncodedType(length=1023), nullable=False),
    sa.Column('captain_pos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('gid'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('role',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.Integer(), nullable=False),
    sa.Column('role_type', werewolf.models.base.EnumType(), nullable=False),
    sa.Column('group_type', werewolf.models.base.EnumType(), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('voteable', sa.Boolean(), nullable=False),
    sa.Column('speakable', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('skills', werewolf.models.base.JSONEncodedType(length=255), nullable=False),
    sa.Column('tags', werewolf.models.base.JSONEncodedType(length=255), nullable=False),
    sa.Column('args', werewolf.models.base.JSONEncodedType(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_role_gid'), 'role', ['gid'], unique=False)
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_gid'), table_name='role')
    op.drop_table('role')
    op.drop_table('game')
    # ### end Alembic commands ###
